### ISSUE TITLE
Payment still in the Ti API docs

### ISSUE THREAD

**Issue by mattcobb** [attdevsupport/ATT_APIPlatform_Appcelerator_Titanium#22]
I found some traces of payment in the Ti repo develop branch.  

These two files contain references to payment:

Docs/source/attTitaniumAPI.html
Docs/output/ATT.js

This one needs to be removed:
Docs/output/ATT.Payment.js

You can also see them in the release ZIP Docs....
![image](https://cloud.githubusercontent.com/assets/893006/5290689/037a0da2-7afe-11e4-942b-a44e6177e886.png)

**Comment by tarasklimenko** [comment]
Removed. Confirmed fixed.
